# Generated by Django 4.1.5 on 2024-02-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('Punch_Card_NO', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=25)),
                ('Designation', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('DOB', models.DateField()),
                ('DOJ', models.DateField()),
                ('DOL', models.DateField()),
                ('Parents_Name', models.CharField(max_length=25)),
                ('Martial_Status', models.CharField(max_length=25)),
                ('Permanent_Address', models.TextField()),
                ('Present_Address', models.TextField()),
                ('Blood_Group', models.CharField(max_length=10)),
                ('UAN_Number', models.IntegerField(null=True, unique=True)),
                ('PF_PW', models.IntegerField()),
                ('ESI_Number', models.IntegerField()),
                ('Mobile_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Aadhar_No', models.IntegerField()),
                ('PAN', models.CharField(max_length=25)),
                ('Bank_Acc_NO', models.IntegerField()),
                ('IFSC_Code', models.CharField(max_length=25)),
                ('Bank_Name', models.CharField(max_length=25)),
                ('Emergency_Contact_No', models.IntegerField()),
                ('Contact_No', models.IntegerField()),
                ('Sur_name', models.CharField(max_length=25)),
                ('Qualification', models.CharField(max_length=25)),
                ('Experience', models.CharField(max_length=25)),
                ('Remarks', models.TextField()),
                ('Salary', models.IntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_id', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Stock_out',
            fields=[
                ('Stock_out_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity_given', models.IntegerField()),
                ('Date_given', models.DateField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
            options={
                'db_table': 'Stock_out',
            },
        ),
        migrations.CreateModel(
            name='Stock_in',
            fields=[
                ('Stock_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity_available', models.IntegerField()),
                ('Date_added', models.DateField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
            ],
            options={
                'db_table': 'Stock_in',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Purchase_Date', models.DateField()),
                ('Invoice_Number', models.DateField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.item')),
                ('Supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.supplier')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
            options={
                'db_table': 'Attendance',
            },
        ),
    ]
