# Generated by Django 4.2.9 on 2024-02-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Supplier_id',
        ),
        migrations.RemoveField(
            model_name='stock_in',
            name='Item',
        ),
        migrations.RemoveField(
            model_name='stock_out',
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='stock_out',
            name='Item_id',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stock_in',
        ),
        migrations.DeleteModel(
            name='Stock_out',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
