# Generated by Django 4.2.9 on 2024-02-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Supplier_id',
            new_name='Supplier',
        ),
    ]
