# Generated by Django 4.2.9 on 2024-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_supplier_id_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Invoice_Number',
            field=models.IntegerField(),
        ),
    ]
